// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: rebecca/node/v1/node.proto

package nodev1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	NodeControlService_Hello_FullMethodName   = "/rebecca.node.v1.NodeControlService/Hello"
	NodeControlService_Connect_FullMethodName = "/rebecca.node.v1.NodeControlService/Connect"
	NodeControlService_Health_FullMethodName  = "/rebecca.node.v1.NodeControlService/Health"
)

// NodeControlServiceClient is the client API for NodeControlService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type NodeControlServiceClient interface {
	Hello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloResponse, error)
	Connect(ctx context.Context, in *ConnectRequest, opts ...grpc.CallOption) (*ConnectResponse, error)
	Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error)
}

type nodeControlServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewNodeControlServiceClient(cc grpc.ClientConnInterface) NodeControlServiceClient {
	return &nodeControlServiceClient{cc}
}

func (c *nodeControlServiceClient) Hello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HelloResponse)
	err := c.cc.Invoke(ctx, NodeControlService_Hello_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeControlServiceClient) Connect(ctx context.Context, in *ConnectRequest, opts ...grpc.CallOption) (*ConnectResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ConnectResponse)
	err := c.cc.Invoke(ctx, NodeControlService_Connect_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeControlServiceClient) Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthResponse)
	err := c.cc.Invoke(ctx, NodeControlService_Health_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// NodeControlServiceServer is the server API for NodeControlService service.
// All implementations must embed UnimplementedNodeControlServiceServer
// for forward compatibility.
type NodeControlServiceServer interface {
	Hello(context.Context, *HelloRequest) (*HelloResponse, error)
	Connect(context.Context, *ConnectRequest) (*ConnectResponse, error)
	Health(context.Context, *HealthRequest) (*HealthResponse, error)
	mustEmbedUnimplementedNodeControlServiceServer()
}

// UnimplementedNodeControlServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedNodeControlServiceServer struct{}

func (UnimplementedNodeControlServiceServer) Hello(context.Context, *HelloRequest) (*HelloResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Hello not implemented")
}
func (UnimplementedNodeControlServiceServer) Connect(context.Context, *ConnectRequest) (*ConnectResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Connect not implemented")
}
func (UnimplementedNodeControlServiceServer) Health(context.Context, *HealthRequest) (*HealthResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Health not implemented")
}
func (UnimplementedNodeControlServiceServer) mustEmbedUnimplementedNodeControlServiceServer() {}
func (UnimplementedNodeControlServiceServer) testEmbeddedByValue()                            {}

// UnsafeNodeControlServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to NodeControlServiceServer will
// result in compilation errors.
type UnsafeNodeControlServiceServer interface {
	mustEmbedUnimplementedNodeControlServiceServer()
}

func RegisterNodeControlServiceServer(s grpc.ServiceRegistrar, srv NodeControlServiceServer) {
	// If the following call pancis, it indicates UnimplementedNodeControlServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&NodeControlService_ServiceDesc, srv)
}

func _NodeControlService_Hello_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HelloRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeControlServiceServer).Hello(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeControlService_Hello_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeControlServiceServer).Hello(ctx, req.(*HelloRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeControlService_Connect_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConnectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeControlServiceServer).Connect(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeControlService_Connect_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeControlServiceServer).Connect(ctx, req.(*ConnectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeControlService_Health_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeControlServiceServer).Health(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeControlService_Health_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeControlServiceServer).Health(ctx, req.(*HealthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// NodeControlService_ServiceDesc is the grpc.ServiceDesc for NodeControlService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var NodeControlService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "rebecca.node.v1.NodeControlService",
	HandlerType: (*NodeControlServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Hello",
			Handler:    _NodeControlService_Hello_Handler,
		},
		{
			MethodName: "Connect",
			Handler:    _NodeControlService_Connect_Handler,
		},
		{
			MethodName: "Health",
			Handler:    _NodeControlService_Health_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "rebecca/node/v1/node.proto",
}

const (
	NodeRuntimeService_StartRuntime_FullMethodName   = "/rebecca.node.v1.NodeRuntimeService/StartRuntime"
	NodeRuntimeService_RestartRuntime_FullMethodName = "/rebecca.node.v1.NodeRuntimeService/RestartRuntime"
	NodeRuntimeService_StopRuntime_FullMethodName    = "/rebecca.node.v1.NodeRuntimeService/StopRuntime"
	NodeRuntimeService_SyncConfig_FullMethodName     = "/rebecca.node.v1.NodeRuntimeService/SyncConfig"
	NodeRuntimeService_AddUser_FullMethodName        = "/rebecca.node.v1.NodeRuntimeService/AddUser"
	NodeRuntimeService_UpdateUser_FullMethodName     = "/rebecca.node.v1.NodeRuntimeService/UpdateUser"
	NodeRuntimeService_RemoveUser_FullMethodName     = "/rebecca.node.v1.NodeRuntimeService/RemoveUser"
	NodeRuntimeService_Metrics_FullMethodName        = "/rebecca.node.v1.NodeRuntimeService/Metrics"
	NodeRuntimeService_UpdateRuntime_FullMethodName  = "/rebecca.node.v1.NodeRuntimeService/UpdateRuntime"
	NodeRuntimeService_UpdateGeo_FullMethodName      = "/rebecca.node.v1.NodeRuntimeService/UpdateGeo"
	NodeRuntimeService_RestartService_FullMethodName = "/rebecca.node.v1.NodeRuntimeService/RestartService"
	NodeRuntimeService_UpdateService_FullMethodName  = "/rebecca.node.v1.NodeRuntimeService/UpdateService"
)

// NodeRuntimeServiceClient is the client API for NodeRuntimeService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type NodeRuntimeServiceClient interface {
	StartRuntime(ctx context.Context, in *RuntimeConfigRequest, opts ...grpc.CallOption) (*RuntimeActionResponse, error)
	RestartRuntime(ctx context.Context, in *RuntimeConfigRequest, opts ...grpc.CallOption) (*RuntimeActionResponse, error)
	StopRuntime(ctx context.Context, in *StopRuntimeRequest, opts ...grpc.CallOption) (*RuntimeActionResponse, error)
	SyncConfig(ctx context.Context, in *RuntimeConfigRequest, opts ...grpc.CallOption) (*RuntimeActionResponse, error)
	AddUser(ctx context.Context, in *InboundUserRequest, opts ...grpc.CallOption) (*RuntimeActionResponse, error)
	UpdateUser(ctx context.Context, in *InboundUserRequest, opts ...grpc.CallOption) (*RuntimeActionResponse, error)
	RemoveUser(ctx context.Context, in *RemoveInboundUserRequest, opts ...grpc.CallOption) (*RuntimeActionResponse, error)
	Metrics(ctx context.Context, in *MetricsRequest, opts ...grpc.CallOption) (*MetricsResponse, error)
	UpdateRuntime(ctx context.Context, in *RuntimeUpdateRequest, opts ...grpc.CallOption) (*RuntimeActionResponse, error)
	UpdateGeo(ctx context.Context, in *GeoUpdateRequest, opts ...grpc.CallOption) (*RuntimeActionResponse, error)
	RestartService(ctx context.Context, in *ServiceRestartRequest, opts ...grpc.CallOption) (*RuntimeActionResponse, error)
	UpdateService(ctx context.Context, in *ServiceUpdateRequest, opts ...grpc.CallOption) (*RuntimeActionResponse, error)
}

type nodeRuntimeServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewNodeRuntimeServiceClient(cc grpc.ClientConnInterface) NodeRuntimeServiceClient {
	return &nodeRuntimeServiceClient{cc}
}

func (c *nodeRuntimeServiceClient) StartRuntime(ctx context.Context, in *RuntimeConfigRequest, opts ...grpc.CallOption) (*RuntimeActionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RuntimeActionResponse)
	err := c.cc.Invoke(ctx, NodeRuntimeService_StartRuntime_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeRuntimeServiceClient) RestartRuntime(ctx context.Context, in *RuntimeConfigRequest, opts ...grpc.CallOption) (*RuntimeActionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RuntimeActionResponse)
	err := c.cc.Invoke(ctx, NodeRuntimeService_RestartRuntime_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeRuntimeServiceClient) StopRuntime(ctx context.Context, in *StopRuntimeRequest, opts ...grpc.CallOption) (*RuntimeActionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RuntimeActionResponse)
	err := c.cc.Invoke(ctx, NodeRuntimeService_StopRuntime_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeRuntimeServiceClient) SyncConfig(ctx context.Context, in *RuntimeConfigRequest, opts ...grpc.CallOption) (*RuntimeActionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RuntimeActionResponse)
	err := c.cc.Invoke(ctx, NodeRuntimeService_SyncConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeRuntimeServiceClient) AddUser(ctx context.Context, in *InboundUserRequest, opts ...grpc.CallOption) (*RuntimeActionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RuntimeActionResponse)
	err := c.cc.Invoke(ctx, NodeRuntimeService_AddUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeRuntimeServiceClient) UpdateUser(ctx context.Context, in *InboundUserRequest, opts ...grpc.CallOption) (*RuntimeActionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RuntimeActionResponse)
	err := c.cc.Invoke(ctx, NodeRuntimeService_UpdateUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeRuntimeServiceClient) RemoveUser(ctx context.Context, in *RemoveInboundUserRequest, opts ...grpc.CallOption) (*RuntimeActionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RuntimeActionResponse)
	err := c.cc.Invoke(ctx, NodeRuntimeService_RemoveUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeRuntimeServiceClient) Metrics(ctx context.Context, in *MetricsRequest, opts ...grpc.CallOption) (*MetricsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MetricsResponse)
	err := c.cc.Invoke(ctx, NodeRuntimeService_Metrics_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeRuntimeServiceClient) UpdateRuntime(ctx context.Context, in *RuntimeUpdateRequest, opts ...grpc.CallOption) (*RuntimeActionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RuntimeActionResponse)
	err := c.cc.Invoke(ctx, NodeRuntimeService_UpdateRuntime_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeRuntimeServiceClient) UpdateGeo(ctx context.Context, in *GeoUpdateRequest, opts ...grpc.CallOption) (*RuntimeActionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RuntimeActionResponse)
	err := c.cc.Invoke(ctx, NodeRuntimeService_UpdateGeo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeRuntimeServiceClient) RestartService(ctx context.Context, in *ServiceRestartRequest, opts ...grpc.CallOption) (*RuntimeActionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RuntimeActionResponse)
	err := c.cc.Invoke(ctx, NodeRuntimeService_RestartService_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeRuntimeServiceClient) UpdateService(ctx context.Context, in *ServiceUpdateRequest, opts ...grpc.CallOption) (*RuntimeActionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RuntimeActionResponse)
	err := c.cc.Invoke(ctx, NodeRuntimeService_UpdateService_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// NodeRuntimeServiceServer is the server API for NodeRuntimeService service.
// All implementations must embed UnimplementedNodeRuntimeServiceServer
// for forward compatibility.
type NodeRuntimeServiceServer interface {
	StartRuntime(context.Context, *RuntimeConfigRequest) (*RuntimeActionResponse, error)
	RestartRuntime(context.Context, *RuntimeConfigRequest) (*RuntimeActionResponse, error)
	StopRuntime(context.Context, *StopRuntimeRequest) (*RuntimeActionResponse, error)
	SyncConfig(context.Context, *RuntimeConfigRequest) (*RuntimeActionResponse, error)
	AddUser(context.Context, *InboundUserRequest) (*RuntimeActionResponse, error)
	UpdateUser(context.Context, *InboundUserRequest) (*RuntimeActionResponse, error)
	RemoveUser(context.Context, *RemoveInboundUserRequest) (*RuntimeActionResponse, error)
	Metrics(context.Context, *MetricsRequest) (*MetricsResponse, error)
	UpdateRuntime(context.Context, *RuntimeUpdateRequest) (*RuntimeActionResponse, error)
	UpdateGeo(context.Context, *GeoUpdateRequest) (*RuntimeActionResponse, error)
	RestartService(context.Context, *ServiceRestartRequest) (*RuntimeActionResponse, error)
	UpdateService(context.Context, *ServiceUpdateRequest) (*RuntimeActionResponse, error)
	mustEmbedUnimplementedNodeRuntimeServiceServer()
}

// UnimplementedNodeRuntimeServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedNodeRuntimeServiceServer struct{}

func (UnimplementedNodeRuntimeServiceServer) StartRuntime(context.Context, *RuntimeConfigRequest) (*RuntimeActionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StartRuntime not implemented")
}
func (UnimplementedNodeRuntimeServiceServer) RestartRuntime(context.Context, *RuntimeConfigRequest) (*RuntimeActionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RestartRuntime not implemented")
}
func (UnimplementedNodeRuntimeServiceServer) StopRuntime(context.Context, *StopRuntimeRequest) (*RuntimeActionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StopRuntime not implemented")
}
func (UnimplementedNodeRuntimeServiceServer) SyncConfig(context.Context, *RuntimeConfigRequest) (*RuntimeActionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SyncConfig not implemented")
}
func (UnimplementedNodeRuntimeServiceServer) AddUser(context.Context, *InboundUserRequest) (*RuntimeActionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddUser not implemented")
}
func (UnimplementedNodeRuntimeServiceServer) UpdateUser(context.Context, *InboundUserRequest) (*RuntimeActionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateUser not implemented")
}
func (UnimplementedNodeRuntimeServiceServer) RemoveUser(context.Context, *RemoveInboundUserRequest) (*RuntimeActionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RemoveUser not implemented")
}
func (UnimplementedNodeRuntimeServiceServer) Metrics(context.Context, *MetricsRequest) (*MetricsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Metrics not implemented")
}
func (UnimplementedNodeRuntimeServiceServer) UpdateRuntime(context.Context, *RuntimeUpdateRequest) (*RuntimeActionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateRuntime not implemented")
}
func (UnimplementedNodeRuntimeServiceServer) UpdateGeo(context.Context, *GeoUpdateRequest) (*RuntimeActionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateGeo not implemented")
}
func (UnimplementedNodeRuntimeServiceServer) RestartService(context.Context, *ServiceRestartRequest) (*RuntimeActionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RestartService not implemented")
}
func (UnimplementedNodeRuntimeServiceServer) UpdateService(context.Context, *ServiceUpdateRequest) (*RuntimeActionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateService not implemented")
}
func (UnimplementedNodeRuntimeServiceServer) mustEmbedUnimplementedNodeRuntimeServiceServer() {}
func (UnimplementedNodeRuntimeServiceServer) testEmbeddedByValue()                            {}

// UnsafeNodeRuntimeServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to NodeRuntimeServiceServer will
// result in compilation errors.
type UnsafeNodeRuntimeServiceServer interface {
	mustEmbedUnimplementedNodeRuntimeServiceServer()
}

func RegisterNodeRuntimeServiceServer(s grpc.ServiceRegistrar, srv NodeRuntimeServiceServer) {
	// If the following call pancis, it indicates UnimplementedNodeRuntimeServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&NodeRuntimeService_ServiceDesc, srv)
}

func _NodeRuntimeService_StartRuntime_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RuntimeConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeRuntimeServiceServer).StartRuntime(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeRuntimeService_StartRuntime_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeRuntimeServiceServer).StartRuntime(ctx, req.(*RuntimeConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeRuntimeService_RestartRuntime_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RuntimeConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeRuntimeServiceServer).RestartRuntime(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeRuntimeService_RestartRuntime_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeRuntimeServiceServer).RestartRuntime(ctx, req.(*RuntimeConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeRuntimeService_StopRuntime_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StopRuntimeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeRuntimeServiceServer).StopRuntime(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeRuntimeService_StopRuntime_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeRuntimeServiceServer).StopRuntime(ctx, req.(*StopRuntimeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeRuntimeService_SyncConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RuntimeConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeRuntimeServiceServer).SyncConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeRuntimeService_SyncConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeRuntimeServiceServer).SyncConfig(ctx, req.(*RuntimeConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeRuntimeService_AddUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InboundUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeRuntimeServiceServer).AddUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeRuntimeService_AddUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeRuntimeServiceServer).AddUser(ctx, req.(*InboundUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeRuntimeService_UpdateUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InboundUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeRuntimeServiceServer).UpdateUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeRuntimeService_UpdateUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeRuntimeServiceServer).UpdateUser(ctx, req.(*InboundUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeRuntimeService_RemoveUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveInboundUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeRuntimeServiceServer).RemoveUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeRuntimeService_RemoveUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeRuntimeServiceServer).RemoveUser(ctx, req.(*RemoveInboundUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeRuntimeService_Metrics_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MetricsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeRuntimeServiceServer).Metrics(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeRuntimeService_Metrics_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeRuntimeServiceServer).Metrics(ctx, req.(*MetricsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeRuntimeService_UpdateRuntime_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RuntimeUpdateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeRuntimeServiceServer).UpdateRuntime(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeRuntimeService_UpdateRuntime_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeRuntimeServiceServer).UpdateRuntime(ctx, req.(*RuntimeUpdateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeRuntimeService_UpdateGeo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GeoUpdateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeRuntimeServiceServer).UpdateGeo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeRuntimeService_UpdateGeo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeRuntimeServiceServer).UpdateGeo(ctx, req.(*GeoUpdateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeRuntimeService_RestartService_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ServiceRestartRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeRuntimeServiceServer).RestartService(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeRuntimeService_RestartService_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeRuntimeServiceServer).RestartService(ctx, req.(*ServiceRestartRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeRuntimeService_UpdateService_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ServiceUpdateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeRuntimeServiceServer).UpdateService(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeRuntimeService_UpdateService_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeRuntimeServiceServer).UpdateService(ctx, req.(*ServiceUpdateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// NodeRuntimeService_ServiceDesc is the grpc.ServiceDesc for NodeRuntimeService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var NodeRuntimeService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "rebecca.node.v1.NodeRuntimeService",
	HandlerType: (*NodeRuntimeServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "StartRuntime",
			Handler:    _NodeRuntimeService_StartRuntime_Handler,
		},
		{
			MethodName: "RestartRuntime",
			Handler:    _NodeRuntimeService_RestartRuntime_Handler,
		},
		{
			MethodName: "StopRuntime",
			Handler:    _NodeRuntimeService_StopRuntime_Handler,
		},
		{
			MethodName: "SyncConfig",
			Handler:    _NodeRuntimeService_SyncConfig_Handler,
		},
		{
			MethodName: "AddUser",
			Handler:    _NodeRuntimeService_AddUser_Handler,
		},
		{
			MethodName: "UpdateUser",
			Handler:    _NodeRuntimeService_UpdateUser_Handler,
		},
		{
			MethodName: "RemoveUser",
			Handler:    _NodeRuntimeService_RemoveUser_Handler,
		},
		{
			MethodName: "Metrics",
			Handler:    _NodeRuntimeService_Metrics_Handler,
		},
		{
			MethodName: "UpdateRuntime",
			Handler:    _NodeRuntimeService_UpdateRuntime_Handler,
		},
		{
			MethodName: "UpdateGeo",
			Handler:    _NodeRuntimeService_UpdateGeo_Handler,
		},
		{
			MethodName: "RestartService",
			Handler:    _NodeRuntimeService_RestartService_Handler,
		},
		{
			MethodName: "UpdateService",
			Handler:    _NodeRuntimeService_UpdateService_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "rebecca/node/v1/node.proto",
}

const (
	NodeUsageService_CollectUserUsage_FullMethodName     = "/rebecca.node.v1.NodeUsageService/CollectUserUsage"
	NodeUsageService_AckUserUsage_FullMethodName         = "/rebecca.node.v1.NodeUsageService/AckUserUsage"
	NodeUsageService_CollectOutboundUsage_FullMethodName = "/rebecca.node.v1.NodeUsageService/CollectOutboundUsage"
	NodeUsageService_AckOutboundUsage_FullMethodName     = "/rebecca.node.v1.NodeUsageService/AckOutboundUsage"
)

// NodeUsageServiceClient is the client API for NodeUsageService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type NodeUsageServiceClient interface {
	CollectUserUsage(ctx context.Context, in *CollectUsageRequest, opts ...grpc.CallOption) (*UserUsageBatch, error)
	AckUserUsage(ctx context.Context, in *AckUsageRequest, opts ...grpc.CallOption) (*AckUsageResponse, error)
	CollectOutboundUsage(ctx context.Context, in *CollectUsageRequest, opts ...grpc.CallOption) (*OutboundUsageBatch, error)
	AckOutboundUsage(ctx context.Context, in *AckUsageRequest, opts ...grpc.CallOption) (*AckUsageResponse, error)
}

type nodeUsageServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewNodeUsageServiceClient(cc grpc.ClientConnInterface) NodeUsageServiceClient {
	return &nodeUsageServiceClient{cc}
}

func (c *nodeUsageServiceClient) CollectUserUsage(ctx context.Context, in *CollectUsageRequest, opts ...grpc.CallOption) (*UserUsageBatch, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UserUsageBatch)
	err := c.cc.Invoke(ctx, NodeUsageService_CollectUserUsage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeUsageServiceClient) AckUserUsage(ctx context.Context, in *AckUsageRequest, opts ...grpc.CallOption) (*AckUsageResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AckUsageResponse)
	err := c.cc.Invoke(ctx, NodeUsageService_AckUserUsage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeUsageServiceClient) CollectOutboundUsage(ctx context.Context, in *CollectUsageRequest, opts ...grpc.CallOption) (*OutboundUsageBatch, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OutboundUsageBatch)
	err := c.cc.Invoke(ctx, NodeUsageService_CollectOutboundUsage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeUsageServiceClient) AckOutboundUsage(ctx context.Context, in *AckUsageRequest, opts ...grpc.CallOption) (*AckUsageResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AckUsageResponse)
	err := c.cc.Invoke(ctx, NodeUsageService_AckOutboundUsage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// NodeUsageServiceServer is the server API for NodeUsageService service.
// All implementations must embed UnimplementedNodeUsageServiceServer
// for forward compatibility.
type NodeUsageServiceServer interface {
	CollectUserUsage(context.Context, *CollectUsageRequest) (*UserUsageBatch, error)
	AckUserUsage(context.Context, *AckUsageRequest) (*AckUsageResponse, error)
	CollectOutboundUsage(context.Context, *CollectUsageRequest) (*OutboundUsageBatch, error)
	AckOutboundUsage(context.Context, *AckUsageRequest) (*AckUsageResponse, error)
	mustEmbedUnimplementedNodeUsageServiceServer()
}

// UnimplementedNodeUsageServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedNodeUsageServiceServer struct{}

func (UnimplementedNodeUsageServiceServer) CollectUserUsage(context.Context, *CollectUsageRequest) (*UserUsageBatch, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CollectUserUsage not implemented")
}
func (UnimplementedNodeUsageServiceServer) AckUserUsage(context.Context, *AckUsageRequest) (*AckUsageResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AckUserUsage not implemented")
}
func (UnimplementedNodeUsageServiceServer) CollectOutboundUsage(context.Context, *CollectUsageRequest) (*OutboundUsageBatch, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CollectOutboundUsage not implemented")
}
func (UnimplementedNodeUsageServiceServer) AckOutboundUsage(context.Context, *AckUsageRequest) (*AckUsageResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AckOutboundUsage not implemented")
}
func (UnimplementedNodeUsageServiceServer) mustEmbedUnimplementedNodeUsageServiceServer() {}
func (UnimplementedNodeUsageServiceServer) testEmbeddedByValue()                          {}

// UnsafeNodeUsageServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to NodeUsageServiceServer will
// result in compilation errors.
type UnsafeNodeUsageServiceServer interface {
	mustEmbedUnimplementedNodeUsageServiceServer()
}

func RegisterNodeUsageServiceServer(s grpc.ServiceRegistrar, srv NodeUsageServiceServer) {
	// If the following call pancis, it indicates UnimplementedNodeUsageServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&NodeUsageService_ServiceDesc, srv)
}

func _NodeUsageService_CollectUserUsage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CollectUsageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeUsageServiceServer).CollectUserUsage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeUsageService_CollectUserUsage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeUsageServiceServer).CollectUserUsage(ctx, req.(*CollectUsageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeUsageService_AckUserUsage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AckUsageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeUsageServiceServer).AckUserUsage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeUsageService_AckUserUsage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeUsageServiceServer).AckUserUsage(ctx, req.(*AckUsageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeUsageService_CollectOutboundUsage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CollectUsageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeUsageServiceServer).CollectOutboundUsage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeUsageService_CollectOutboundUsage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeUsageServiceServer).CollectOutboundUsage(ctx, req.(*CollectUsageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeUsageService_AckOutboundUsage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AckUsageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeUsageServiceServer).AckOutboundUsage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeUsageService_AckOutboundUsage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeUsageServiceServer).AckOutboundUsage(ctx, req.(*AckUsageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// NodeUsageService_ServiceDesc is the grpc.ServiceDesc for NodeUsageService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var NodeUsageService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "rebecca.node.v1.NodeUsageService",
	HandlerType: (*NodeUsageServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CollectUserUsage",
			Handler:    _NodeUsageService_CollectUserUsage_Handler,
		},
		{
			MethodName: "AckUserUsage",
			Handler:    _NodeUsageService_AckUserUsage_Handler,
		},
		{
			MethodName: "CollectOutboundUsage",
			Handler:    _NodeUsageService_CollectOutboundUsage_Handler,
		},
		{
			MethodName: "AckOutboundUsage",
			Handler:    _NodeUsageService_AckOutboundUsage_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "rebecca/node/v1/node.proto",
}

const (
	NodeLogsService_StreamLogs_FullMethodName = "/rebecca.node.v1.NodeLogsService/StreamLogs"
)

// NodeLogsServiceClient is the client API for NodeLogsService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type NodeLogsServiceClient interface {
	StreamLogs(ctx context.Context, in *StreamLogsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[LogLine], error)
}

type nodeLogsServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewNodeLogsServiceClient(cc grpc.ClientConnInterface) NodeLogsServiceClient {
	return &nodeLogsServiceClient{cc}
}

func (c *nodeLogsServiceClient) StreamLogs(ctx context.Context, in *StreamLogsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[LogLine], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &NodeLogsService_ServiceDesc.Streams[0], NodeLogsService_StreamLogs_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[StreamLogsRequest, LogLine]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type NodeLogsService_StreamLogsClient = grpc.ServerStreamingClient[LogLine]

// NodeLogsServiceServer is the server API for NodeLogsService service.
// All implementations must embed UnimplementedNodeLogsServiceServer
// for forward compatibility.
type NodeLogsServiceServer interface {
	StreamLogs(*StreamLogsRequest, grpc.ServerStreamingServer[LogLine]) error
	mustEmbedUnimplementedNodeLogsServiceServer()
}

// UnimplementedNodeLogsServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedNodeLogsServiceServer struct{}

func (UnimplementedNodeLogsServiceServer) StreamLogs(*StreamLogsRequest, grpc.ServerStreamingServer[LogLine]) error {
	return status.Errorf(codes.Unimplemented, "method StreamLogs not implemented")
}
func (UnimplementedNodeLogsServiceServer) mustEmbedUnimplementedNodeLogsServiceServer() {}
func (UnimplementedNodeLogsServiceServer) testEmbeddedByValue()                         {}

// UnsafeNodeLogsServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to NodeLogsServiceServer will
// result in compilation errors.
type UnsafeNodeLogsServiceServer interface {
	mustEmbedUnimplementedNodeLogsServiceServer()
}

func RegisterNodeLogsServiceServer(s grpc.ServiceRegistrar, srv NodeLogsServiceServer) {
	// If the following call pancis, it indicates UnimplementedNodeLogsServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&NodeLogsService_ServiceDesc, srv)
}

func _NodeLogsService_StreamLogs_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StreamLogsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(NodeLogsServiceServer).StreamLogs(m, &grpc.GenericServerStream[StreamLogsRequest, LogLine]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type NodeLogsService_StreamLogsServer = grpc.ServerStreamingServer[LogLine]

// NodeLogsService_ServiceDesc is the grpc.ServiceDesc for NodeLogsService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var NodeLogsService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "rebecca.node.v1.NodeLogsService",
	HandlerType: (*NodeLogsServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamLogs",
			Handler:       _NodeLogsService_StreamLogs_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "rebecca/node/v1/node.proto",
}
