// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: rebecca/node/v1/node.proto

package nodev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_rebecca_node_v1_node_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_rebecca_node_v1_node_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_rebecca_node_v1_node_proto_rawDescGZIP(), []int{0}
}

type HelloRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MasterId      string                 `protobuf:"bytes,1,opt,name=master_id,json=masterId,proto3" json:"master_id,omitempty"`
	MasterVersion string                 `protobuf:"bytes,2,opt,name=master_version,json=masterVersion,proto3" json:"master_version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HelloRequest) Reset() {
	*x = HelloRequest{}
	mi := &file_rebecca_node_v1_node_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HelloRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HelloRequest) ProtoMessage() {}

func (x *HelloRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rebecca_node_v1_node_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HelloRequest.ProtoReflect.Descriptor instead.
func (*HelloRequest) Descriptor() ([]byte, []int) {
	return file_rebecca_node_v1_node_proto_rawDescGZIP(), []int{1}
}

func (x *HelloRequest) GetMasterId() string {
	if x != nil {
		return x.MasterId
	}
	return ""
}

func (x *HelloRequest) GetMasterVersion() string {
	if x != nil {
		return x.MasterVersion
	}
	return ""
}

type HelloResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	NodeName      string                 `protobuf:"bytes,2,opt,name=node_name,json=nodeName,proto3" json:"node_name,omitempty"`
	NodeVersion   string                 `protobuf:"bytes,3,opt,name=node_version,json=nodeVersion,proto3" json:"node_version,omitempty"`
	InstallMode   string                 `protobuf:"bytes,4,opt,name=install_mode,json=installMode,proto3" json:"install_mode,omitempty"`
	UpdateChannel string                 `protobuf:"bytes,5,opt,name=update_channel,json=updateChannel,proto3" json:"update_channel,omitempty"`
	Runtime       *RuntimeState          `protobuf:"bytes,6,opt,name=runtime,proto3" json:"runtime,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HelloResponse) Reset() {
	*x = HelloResponse{}
	mi := &file_rebecca_node_v1_node_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HelloResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HelloResponse) ProtoMessage() {}

func (x *HelloResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rebecca_node_v1_node_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HelloResponse.ProtoReflect.Descriptor instead.
func (*HelloResponse) Descriptor() ([]byte, []int) {
	return file_rebecca_node_v1_node_proto_rawDescGZIP(), []int{2}
}

func (x *HelloResponse) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *HelloResponse) GetNodeName() string {
	if x != nil {
		return x.NodeName
	}
	return ""
}

func (x *HelloResponse) GetNodeVersion() string {
	if x != nil {
		return x.NodeVersion
	}
	return ""
}

func (x *HelloResponse) GetInstallMode() string {
	if x != nil {
		return x.InstallMode
	}
	return ""
}

func (x *HelloResponse) GetUpdateChannel() string {
	if x != nil {
		return x.UpdateChannel
	}
	return ""
}

func (x *HelloResponse) GetRuntime() *RuntimeState {
	if x != nil {
		return x.Runtime
	}
	return nil
}

type ConnectRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	MasterId         string                 `protobuf:"bytes,1,opt,name=master_id,json=masterId,proto3" json:"master_id,omitempty"`
	MasterVersion    string                 `protobuf:"bytes,2,opt,name=master_version,json=masterVersion,proto3" json:"master_version,omitempty"`
	ExpectedNodeName string                 `protobuf:"bytes,3,opt,name=expected_node_name,json=expectedNodeName,proto3" json:"expected_node_name,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ConnectRequest) Reset() {
	*x = ConnectRequest{}
	mi := &file_rebecca_node_v1_node_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConnectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectRequest) ProtoMessage() {}

func (x *ConnectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rebecca_node_v1_node_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectRequest.ProtoReflect.Descriptor instead.
func (*ConnectRequest) Descriptor() ([]byte, []int) {
	return file_rebecca_node_v1_node_proto_rawDescGZIP(), []int{3}
}

func (x *ConnectRequest) GetMasterId() string {
	if x != nil {
		return x.MasterId
	}
	return ""
}

func (x *ConnectRequest) GetMasterVersion() string {
	if x != nil {
		return x.MasterVersion
	}
	return ""
}

func (x *ConnectRequest) GetExpectedNodeName() string {
	if x != nil {
		return x.ExpectedNodeName
	}
	return ""
}

type ConnectResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ConnectionId  string                 `protobuf:"bytes,1,opt,name=connection_id,json=connectionId,proto3" json:"connection_id,omitempty"`
	Runtime       *RuntimeState          `protobuf:"bytes,2,opt,name=runtime,proto3" json:"runtime,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConnectResponse) Reset() {
	*x = ConnectResponse{}
	mi := &file_rebecca_node_v1_node_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConnectResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectResponse) ProtoMessage() {}

func (x *ConnectResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rebecca_node_v1_node_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectResponse.ProtoReflect.Descriptor instead.
func (*ConnectResponse) Descriptor() ([]byte, []int) {
	return file_rebecca_node_v1_node_proto_rawDescGZIP(), []int{4}
}

func (x *ConnectResponse) GetConnectionId() string {
	if x != nil {
		return x.ConnectionId
	}
	return ""
}

func (x *ConnectResponse) GetRuntime() *RuntimeState {
	if x != nil {
		return x.Runtime
	}
	return nil
}

type HealthRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	IncludeMetrics bool                   `protobuf:"varint,1,opt,name=include_metrics,json=includeMetrics,proto3" json:"include_metrics,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *HealthRequest) Reset() {
	*x = HealthRequest{}
	mi := &file_rebecca_node_v1_node_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthRequest) ProtoMessage() {}

func (x *HealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rebecca_node_v1_node_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthRequest.ProtoReflect.Descriptor instead.
func (*HealthRequest) Descriptor() ([]byte, []int) {
	return file_rebecca_node_v1_node_proto_rawDescGZIP(), []int{5}
}

func (x *HealthRequest) GetIncludeMetrics() bool {
	if x != nil {
		return x.IncludeMetrics
	}
	return false
}

type HealthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Runtime       *RuntimeState          `protobuf:"bytes,1,opt,name=runtime,proto3" json:"runtime,omitempty"`
	Metrics       *MetricsResponse       `protobuf:"bytes,2,opt,name=metrics,proto3" json:"metrics,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthResponse) Reset() {
	*x = HealthResponse{}
	mi := &file_rebecca_node_v1_node_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthResponse) ProtoMessage() {}

func (x *HealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rebecca_node_v1_node_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthResponse.ProtoReflect.Descriptor instead.
func (*HealthResponse) Descriptor() ([]byte, []int) {
	return file_rebecca_node_v1_node_proto_rawDescGZIP(), []int{6}
}

func (x *HealthResponse) GetRuntime() *RuntimeState {
	if x != nil {
		return x.Runtime
	}
	return nil
}

func (x *HealthResponse) GetMetrics() *MetricsResponse {
	if x != nil {
		return x.Metrics
	}
	return nil
}

type RuntimeState struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Connected     bool                   `protobuf:"varint,1,opt,name=connected,proto3" json:"connected,omitempty"`
	Started       bool                   `protobuf:"varint,2,opt,name=started,proto3" json:"started,omitempty"`
	CoreVersion   string                 `protobuf:"bytes,3,opt,name=core_version,json=coreVersion,proto3" json:"core_version,omitempty"`
	NodeVersion   string                 `protobuf:"bytes,4,opt,name=node_version,json=nodeVersion,proto3" json:"node_version,omitempty"`
	InstallMode   string                 `protobuf:"bytes,5,opt,name=install_mode,json=installMode,proto3" json:"install_mode,omitempty"`
	UpdateChannel string                 `protobuf:"bytes,6,opt,name=update_channel,json=updateChannel,proto3" json:"update_channel,omitempty"`
	Message       string                 `protobuf:"bytes,7,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RuntimeState) Reset() {
	*x = RuntimeState{}
	mi := &file_rebecca_node_v1_node_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RuntimeState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RuntimeState) ProtoMessage() {}

func (x *RuntimeState) ProtoReflect() protoreflect.Message {
	mi := &file_rebecca_node_v1_node_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RuntimeState.ProtoReflect.Descriptor instead.
func (*RuntimeState) Descriptor() ([]byte, []int) {
	return file_rebecca_node_v1_node_proto_rawDescGZIP(), []int{7}
}

func (x *RuntimeState) GetConnected() bool {
	if x != nil {
		return x.Connected
	}
	return false
}

func (x *RuntimeState) GetStarted() bool {
	if x != nil {
		return x.Started
	}
	return false
}

func (x *RuntimeState) GetCoreVersion() string {
	if x != nil {
		return x.CoreVersion
	}
	return ""
}

func (x *RuntimeState) GetNodeVersion() string {
	if x != nil {
		return x.NodeVersion
	}
	return ""
}

func (x *RuntimeState) GetInstallMode() string {
	if x != nil {
		return x.InstallMode
	}
	return ""
}

func (x *RuntimeState) GetUpdateChannel() string {
	if x != nil {
		return x.UpdateChannel
	}
	return ""
}

func (x *RuntimeState) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type RuntimeConfigRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	OperationId    string                 `protobuf:"bytes,1,opt,name=operation_id,json=operationId,proto3" json:"operation_id,omitempty"`
	ConfigJson     string                 `protobuf:"bytes,2,opt,name=config_json,json=configJson,proto3" json:"config_json,omitempty"`
	IncludeDbUsers bool                   `protobuf:"varint,3,opt,name=include_db_users,json=includeDbUsers,proto3" json:"include_db_users,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *RuntimeConfigRequest) Reset() {
	*x = RuntimeConfigRequest{}
	mi := &file_rebecca_node_v1_node_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RuntimeConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RuntimeConfigRequest) ProtoMessage() {}

func (x *RuntimeConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rebecca_node_v1_node_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RuntimeConfigRequest.ProtoReflect.Descriptor instead.
func (*RuntimeConfigRequest) Descriptor() ([]byte, []int) {
	return file_rebecca_node_v1_node_proto_rawDescGZIP(), []int{8}
}

func (x *RuntimeConfigRequest) GetOperationId() string {
	if x != nil {
		return x.OperationId
	}
	return ""
}

func (x *RuntimeConfigRequest) GetConfigJson() string {
	if x != nil {
		return x.ConfigJson
	}
	return ""
}

func (x *RuntimeConfigRequest) GetIncludeDbUsers() bool {
	if x != nil {
		return x.IncludeDbUsers
	}
	return false
}

type StopRuntimeRequest struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	OperationId            string                 `protobuf:"bytes,1,opt,name=operation_id,json=operationId,proto3" json:"operation_id,omitempty"`
	CollectUsageBeforeStop bool                   `protobuf:"varint,2,opt,name=collect_usage_before_stop,json=collectUsageBeforeStop,proto3" json:"collect_usage_before_stop,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *StopRuntimeRequest) Reset() {
	*x = StopRuntimeRequest{}
	mi := &file_rebecca_node_v1_node_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopRuntimeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopRuntimeRequest) ProtoMessage() {}

func (x *StopRuntimeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rebecca_node_v1_node_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopRuntimeRequest.ProtoReflect.Descriptor instead.
func (*StopRuntimeRequest) Descriptor() ([]byte, []int) {
	return file_rebecca_node_v1_node_proto_rawDescGZIP(), []int{9}
}

func (x *StopRuntimeRequest) GetOperationId() string {
	if x != nil {
		return x.OperationId
	}
	return ""
}

func (x *StopRuntimeRequest) GetCollectUsageBeforeStop() bool {
	if x != nil {
		return x.CollectUsageBeforeStop
	}
	return false
}

type RuntimeActionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OperationId   string                 `protobuf:"bytes,1,opt,name=operation_id,json=operationId,proto3" json:"operation_id,omitempty"`
	Accepted      bool                   `protobuf:"varint,2,opt,name=accepted,proto3" json:"accepted,omitempty"`
	Runtime       *RuntimeState          `protobuf:"bytes,3,opt,name=runtime,proto3" json:"runtime,omitempty"`
	Message       string                 `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RuntimeActionResponse) Reset() {
	*x = RuntimeActionResponse{}
	mi := &file_rebecca_node_v1_node_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RuntimeActionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RuntimeActionResponse) ProtoMessage() {}

func (x *RuntimeActionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rebecca_node_v1_node_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RuntimeActionResponse.ProtoReflect.Descriptor instead.
func (*RuntimeActionResponse) Descriptor() ([]byte, []int) {
	return file_rebecca_node_v1_node_proto_rawDescGZIP(), []int{10}
}

func (x *RuntimeActionResponse) GetOperationId() string {
	if x != nil {
		return x.OperationId
	}
	return ""
}

func (x *RuntimeActionResponse) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

func (x *RuntimeActionResponse) GetRuntime() *RuntimeState {
	if x != nil {
		return x.Runtime
	}
	return nil
}

func (x *RuntimeActionResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type InboundUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OperationId   string                 `protobuf:"bytes,1,opt,name=operation_id,json=operationId,proto3" json:"operation_id,omitempty"`
	InboundTag    string                 `protobuf:"bytes,2,opt,name=inbound_tag,json=inboundTag,proto3" json:"inbound_tag,omitempty"`
	User          *InboundUser           `protobuf:"bytes,3,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InboundUserRequest) Reset() {
	*x = InboundUserRequest{}
	mi := &file_rebecca_node_v1_node_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InboundUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InboundUserRequest) ProtoMessage() {}

func (x *InboundUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rebecca_node_v1_node_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InboundUserRequest.ProtoReflect.Descriptor instead.
func (*InboundUserRequest) Descriptor() ([]byte, []int) {
	return file_rebecca_node_v1_node_proto_rawDescGZIP(), []int{11}
}

func (x *InboundUserRequest) GetOperationId() string {
	if x != nil {
		return x.OperationId
	}
	return ""
}

func (x *InboundUserRequest) GetInboundTag() string {
	if x != nil {
		return x.InboundTag
	}
	return ""
}

func (x *InboundUserRequest) GetUser() *InboundUser {
	if x != nil {
		return x.User
	}
	return nil
}

type RemoveInboundUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OperationId   string                 `protobuf:"bytes,1,opt,name=operation_id,json=operationId,proto3" json:"operation_id,omitempty"`
	InboundTag    string                 `protobuf:"bytes,2,opt,name=inbound_tag,json=inboundTag,proto3" json:"inbound_tag,omitempty"`
	Email         string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveInboundUserRequest) Reset() {
	*x = RemoveInboundUserRequest{}
	mi := &file_rebecca_node_v1_node_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveInboundUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveInboundUserRequest) ProtoMessage() {}

func (x *RemoveInboundUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rebecca_node_v1_node_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveInboundUserRequest.ProtoReflect.Descriptor instead.
func (*RemoveInboundUserRequest) Descriptor() ([]byte, []int) {
	return file_rebecca_node_v1_node_proto_rawDescGZIP(), []int{12}
}

func (x *RemoveInboundUserRequest) GetOperationId() string {
	if x != nil {
		return x.OperationId
	}
	return ""
}

func (x *RemoveInboundUserRequest) GetInboundTag() string {
	if x != nil {
		return x.InboundTag
	}
	return ""
}

func (x *RemoveInboundUserRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

type InboundUser struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Protocol      string                 `protobuf:"bytes,2,opt,name=protocol,proto3" json:"protocol,omitempty"`
	Fields        map[string]string      `protobuf:"bytes,3,rep,name=fields,proto3" json:"fields,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InboundUser) Reset() {
	*x = InboundUser{}
	mi := &file_rebecca_node_v1_node_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InboundUser) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InboundUser) ProtoMessage() {}

func (x *InboundUser) ProtoReflect() protoreflect.Message {
	mi := &file_rebecca_node_v1_node_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InboundUser.ProtoReflect.Descriptor instead.
func (*InboundUser) Descriptor() ([]byte, []int) {
	return file_rebecca_node_v1_node_proto_rawDescGZIP(), []int{13}
}

func (x *InboundUser) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *InboundUser) GetProtocol() string {
	if x != nil {
		return x.Protocol
	}
	return ""
}

func (x *InboundUser) GetFields() map[string]string {
	if x != nil {
		return x.Fields
	}
	return nil
}

type MetricsRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	IncludeRuntime bool                   `protobuf:"varint,1,opt,name=include_runtime,json=includeRuntime,proto3" json:"include_runtime,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *MetricsRequest) Reset() {
	*x = MetricsRequest{}
	mi := &file_rebecca_node_v1_node_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetricsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetricsRequest) ProtoMessage() {}

func (x *MetricsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rebecca_node_v1_node_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetricsRequest.ProtoReflect.Descriptor instead.
func (*MetricsRequest) Descriptor() ([]byte, []int) {
	return file_rebecca_node_v1_node_proto_rawDescGZIP(), []int{14}
}

func (x *MetricsRequest) GetIncludeRuntime() bool {
	if x != nil {
		return x.IncludeRuntime
	}
	return false
}

type MetricsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Runtime       *RuntimeState          `protobuf:"bytes,1,opt,name=runtime,proto3" json:"runtime,omitempty"`
	System        *SystemMetrics         `protobuf:"bytes,2,opt,name=system,proto3" json:"system,omitempty"`
	Transfer      *TransferMetrics       `protobuf:"bytes,3,opt,name=transfer,proto3" json:"transfer,omitempty"`
	SampledAtUnix int64                  `protobuf:"varint,4,opt,name=sampled_at_unix,json=sampledAtUnix,proto3" json:"sampled_at_unix,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetricsResponse) Reset() {
	*x = MetricsResponse{}
	mi := &file_rebecca_node_v1_node_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetricsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetricsResponse) ProtoMessage() {}

func (x *MetricsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rebecca_node_v1_node_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetricsResponse.ProtoReflect.Descriptor instead.
func (*MetricsResponse) Descriptor() ([]byte, []int) {
	return file_rebecca_node_v1_node_proto_rawDescGZIP(), []int{15}
}

func (x *MetricsResponse) GetRuntime() *RuntimeState {
	if x != nil {
		return x.Runtime
	}
	return nil
}

func (x *MetricsResponse) GetSystem() *SystemMetrics {
	if x != nil {
		return x.System
	}
	return nil
}

func (x *MetricsResponse) GetTransfer() *TransferMetrics {
	if x != nil {
		return x.Transfer
	}
	return nil
}

func (x *MetricsResponse) GetSampledAtUnix() int64 {
	if x != nil {
		return x.SampledAtUnix
	}
	return 0
}

type SystemMetrics struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	CpuCores           int32                  `protobuf:"varint,1,opt,name=cpu_cores,json=cpuCores,proto3" json:"cpu_cores,omitempty"`
	CpuFrequencyHz     float64                `protobuf:"fixed64,2,opt,name=cpu_frequency_hz,json=cpuFrequencyHz,proto3" json:"cpu_frequency_hz,omitempty"`
	CpuUsagePercent    float64                `protobuf:"fixed64,3,opt,name=cpu_usage_percent,json=cpuUsagePercent,proto3" json:"cpu_usage_percent,omitempty"`
	MemoryUsed         uint64                 `protobuf:"varint,4,opt,name=memory_used,json=memoryUsed,proto3" json:"memory_used,omitempty"`
	MemoryTotal        uint64                 `protobuf:"varint,5,opt,name=memory_total,json=memoryTotal,proto3" json:"memory_total,omitempty"`
	MemoryUsagePercent float64                `protobuf:"fixed64,6,opt,name=memory_usage_percent,json=memoryUsagePercent,proto3" json:"memory_usage_percent,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *SystemMetrics) Reset() {
	*x = SystemMetrics{}
	mi := &file_rebecca_node_v1_node_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SystemMetrics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SystemMetrics) ProtoMessage() {}

func (x *SystemMetrics) ProtoReflect() protoreflect.Message {
	mi := &file_rebecca_node_v1_node_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SystemMetrics.ProtoReflect.Descriptor instead.
func (*SystemMetrics) Descriptor() ([]byte, []int) {
	return file_rebecca_node_v1_node_proto_rawDescGZIP(), []int{16}
}

func (x *SystemMetrics) GetCpuCores() int32 {
	if x != nil {
		return x.CpuCores
	}
	return 0
}

func (x *SystemMetrics) GetCpuFrequencyHz() float64 {
	if x != nil {
		return x.CpuFrequencyHz
	}
	return 0
}

func (x *SystemMetrics) GetCpuUsagePercent() float64 {
	if x != nil {
		return x.CpuUsagePercent
	}
	return 0
}

func (x *SystemMetrics) GetMemoryUsed() uint64 {
	if x != nil {
		return x.MemoryUsed
	}
	return 0
}

func (x *SystemMetrics) GetMemoryTotal() uint64 {
	if x != nil {
		return x.MemoryTotal
	}
	return 0
}

func (x *SystemMetrics) GetMemoryUsagePercent() float64 {
	if x != nil {
		return x.MemoryUsagePercent
	}
	return 0
}

type TransferMetrics struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UplinkTotal   uint64                 `protobuf:"varint,1,opt,name=uplink_total,json=uplinkTotal,proto3" json:"uplink_total,omitempty"`
	DownlinkTotal uint64                 `protobuf:"varint,2,opt,name=downlink_total,json=downlinkTotal,proto3" json:"downlink_total,omitempty"`
	UploadSpeed   uint64                 `protobuf:"varint,3,opt,name=upload_speed,json=uploadSpeed,proto3" json:"upload_speed,omitempty"`
	DownloadSpeed uint64                 `protobuf:"varint,4,opt,name=download_speed,json=downloadSpeed,proto3" json:"download_speed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransferMetrics) Reset() {
	*x = TransferMetrics{}
	mi := &file_rebecca_node_v1_node_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransferMetrics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransferMetrics) ProtoMessage() {}

func (x *TransferMetrics) ProtoReflect() protoreflect.Message {
	mi := &file_rebecca_node_v1_node_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransferMetrics.ProtoReflect.Descriptor instead.
func (*TransferMetrics) Descriptor() ([]byte, []int) {
	return file_rebecca_node_v1_node_proto_rawDescGZIP(), []int{17}
}

func (x *TransferMetrics) GetUplinkTotal() uint64 {
	if x != nil {
		return x.UplinkTotal
	}
	return 0
}

func (x *TransferMetrics) GetDownlinkTotal() uint64 {
	if x != nil {
		return x.DownlinkTotal
	}
	return 0
}

func (x *TransferMetrics) GetUploadSpeed() uint64 {
	if x != nil {
		return x.UploadSpeed
	}
	return 0
}

func (x *TransferMetrics) GetDownloadSpeed() uint64 {
	if x != nil {
		return x.DownloadSpeed
	}
	return 0
}

type CollectUsageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CollectorId   string                 `protobuf:"bytes,1,opt,name=collector_id,json=collectorId,proto3" json:"collector_id,omitempty"`
	Reset_        bool                   `protobuf:"varint,2,opt,name=reset,proto3" json:"reset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CollectUsageRequest) Reset() {
	*x = CollectUsageRequest{}
	mi := &file_rebecca_node_v1_node_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CollectUsageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CollectUsageRequest) ProtoMessage() {}

func (x *CollectUsageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rebecca_node_v1_node_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CollectUsageRequest.ProtoReflect.Descriptor instead.
func (*CollectUsageRequest) Descriptor() ([]byte, []int) {
	return file_rebecca_node_v1_node_proto_rawDescGZIP(), []int{18}
}

func (x *CollectUsageRequest) GetCollectorId() string {
	if x != nil {
		return x.CollectorId
	}
	return ""
}

func (x *CollectUsageRequest) GetReset_() bool {
	if x != nil {
		return x.Reset_
	}
	return false
}

type UserUsageBatch struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BatchId       string                 `protobuf:"bytes,1,opt,name=batch_id,json=batchId,proto3" json:"batch_id,omitempty"`
	Stats         []*UserUsageSample     `protobuf:"bytes,2,rep,name=stats,proto3" json:"stats,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserUsageBatch) Reset() {
	*x = UserUsageBatch{}
	mi := &file_rebecca_node_v1_node_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserUsageBatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserUsageBatch) ProtoMessage() {}

func (x *UserUsageBatch) ProtoReflect() protoreflect.Message {
	mi := &file_rebecca_node_v1_node_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserUsageBatch.ProtoReflect.Descriptor instead.
func (*UserUsageBatch) Descriptor() ([]byte, []int) {
	return file_rebecca_node_v1_node_proto_rawDescGZIP(), []int{19}
}

func (x *UserUsageBatch) GetBatchId() string {
	if x != nil {
		return x.BatchId
	}
	return ""
}

func (x *UserUsageBatch) GetStats() []*UserUsageSample {
	if x != nil {
		return x.Stats
	}
	return nil
}

type UserUsageSample struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uid           string                 `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Value         uint64                 `protobuf:"varint,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserUsageSample) Reset() {
	*x = UserUsageSample{}
	mi := &file_rebecca_node_v1_node_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserUsageSample) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserUsageSample) ProtoMessage() {}

func (x *UserUsageSample) ProtoReflect() protoreflect.Message {
	mi := &file_rebecca_node_v1_node_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserUsageSample.ProtoReflect.Descriptor instead.
func (*UserUsageSample) Descriptor() ([]byte, []int) {
	return file_rebecca_node_v1_node_proto_rawDescGZIP(), []int{20}
}

func (x *UserUsageSample) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

func (x *UserUsageSample) GetValue() uint64 {
	if x != nil {
		return x.Value
	}
	return 0
}

type OutboundUsageBatch struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BatchId       string                 `protobuf:"bytes,1,opt,name=batch_id,json=batchId,proto3" json:"batch_id,omitempty"`
	Stats         []*OutboundUsageSample `protobuf:"bytes,2,rep,name=stats,proto3" json:"stats,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OutboundUsageBatch) Reset() {
	*x = OutboundUsageBatch{}
	mi := &file_rebecca_node_v1_node_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OutboundUsageBatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OutboundUsageBatch) ProtoMessage() {}

func (x *OutboundUsageBatch) ProtoReflect() protoreflect.Message {
	mi := &file_rebecca_node_v1_node_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OutboundUsageBatch.ProtoReflect.Descriptor instead.
func (*OutboundUsageBatch) Descriptor() ([]byte, []int) {
	return file_rebecca_node_v1_node_proto_rawDescGZIP(), []int{21}
}

func (x *OutboundUsageBatch) GetBatchId() string {
	if x != nil {
		return x.BatchId
	}
	return ""
}

func (x *OutboundUsageBatch) GetStats() []*OutboundUsageSample {
	if x != nil {
		return x.Stats
	}
	return nil
}

type OutboundUsageSample struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tag           string                 `protobuf:"bytes,1,opt,name=tag,proto3" json:"tag,omitempty"`
	Up            uint64                 `protobuf:"varint,2,opt,name=up,proto3" json:"up,omitempty"`
	Down          uint64                 `protobuf:"varint,3,opt,name=down,proto3" json:"down,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OutboundUsageSample) Reset() {
	*x = OutboundUsageSample{}
	mi := &file_rebecca_node_v1_node_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OutboundUsageSample) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OutboundUsageSample) ProtoMessage() {}

func (x *OutboundUsageSample) ProtoReflect() protoreflect.Message {
	mi := &file_rebecca_node_v1_node_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OutboundUsageSample.ProtoReflect.Descriptor instead.
func (*OutboundUsageSample) Descriptor() ([]byte, []int) {
	return file_rebecca_node_v1_node_proto_rawDescGZIP(), []int{22}
}

func (x *OutboundUsageSample) GetTag() string {
	if x != nil {
		return x.Tag
	}
	return ""
}

func (x *OutboundUsageSample) GetUp() uint64 {
	if x != nil {
		return x.Up
	}
	return 0
}

func (x *OutboundUsageSample) GetDown() uint64 {
	if x != nil {
		return x.Down
	}
	return 0
}

type AckUsageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BatchId       string                 `protobuf:"bytes,1,opt,name=batch_id,json=batchId,proto3" json:"batch_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AckUsageRequest) Reset() {
	*x = AckUsageRequest{}
	mi := &file_rebecca_node_v1_node_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AckUsageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AckUsageRequest) ProtoMessage() {}

func (x *AckUsageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rebecca_node_v1_node_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AckUsageRequest.ProtoReflect.Descriptor instead.
func (*AckUsageRequest) Descriptor() ([]byte, []int) {
	return file_rebecca_node_v1_node_proto_rawDescGZIP(), []int{23}
}

func (x *AckUsageRequest) GetBatchId() string {
	if x != nil {
		return x.BatchId
	}
	return ""
}

type AckUsageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BatchId       string                 `protobuf:"bytes,1,opt,name=batch_id,json=batchId,proto3" json:"batch_id,omitempty"`
	Acknowledged  bool                   `protobuf:"varint,2,opt,name=acknowledged,proto3" json:"acknowledged,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AckUsageResponse) Reset() {
	*x = AckUsageResponse{}
	mi := &file_rebecca_node_v1_node_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AckUsageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AckUsageResponse) ProtoMessage() {}

func (x *AckUsageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rebecca_node_v1_node_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AckUsageResponse.ProtoReflect.Descriptor instead.
func (*AckUsageResponse) Descriptor() ([]byte, []int) {
	return file_rebecca_node_v1_node_proto_rawDescGZIP(), []int{24}
}

func (x *AckUsageResponse) GetBatchId() string {
	if x != nil {
		return x.BatchId
	}
	return ""
}

func (x *AckUsageResponse) GetAcknowledged() bool {
	if x != nil {
		return x.Acknowledged
	}
	return false
}

type StreamLogsRequest struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	StreamId             string                 `protobuf:"bytes,1,opt,name=stream_id,json=streamId,proto3" json:"stream_id,omitempty"`
	MaxLines             uint32                 `protobuf:"varint,2,opt,name=max_lines,json=maxLines,proto3" json:"max_lines,omitempty"`
	FlushIntervalSeconds float64                `protobuf:"fixed64,3,opt,name=flush_interval_seconds,json=flushIntervalSeconds,proto3" json:"flush_interval_seconds,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *StreamLogsRequest) Reset() {
	*x = StreamLogsRequest{}
	mi := &file_rebecca_node_v1_node_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamLogsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamLogsRequest) ProtoMessage() {}

func (x *StreamLogsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rebecca_node_v1_node_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamLogsRequest.ProtoReflect.Descriptor instead.
func (*StreamLogsRequest) Descriptor() ([]byte, []int) {
	return file_rebecca_node_v1_node_proto_rawDescGZIP(), []int{25}
}

func (x *StreamLogsRequest) GetStreamId() string {
	if x != nil {
		return x.StreamId
	}
	return ""
}

func (x *StreamLogsRequest) GetMaxLines() uint32 {
	if x != nil {
		return x.MaxLines
	}
	return 0
}

func (x *StreamLogsRequest) GetFlushIntervalSeconds() float64 {
	if x != nil {
		return x.FlushIntervalSeconds
	}
	return 0
}

type LogLine struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StreamId      string                 `protobuf:"bytes,1,opt,name=stream_id,json=streamId,proto3" json:"stream_id,omitempty"`
	Line          string                 `protobuf:"bytes,2,opt,name=line,proto3" json:"line,omitempty"`
	EmittedAtUnix int64                  `protobuf:"varint,3,opt,name=emitted_at_unix,json=emittedAtUnix,proto3" json:"emitted_at_unix,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogLine) Reset() {
	*x = LogLine{}
	mi := &file_rebecca_node_v1_node_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogLine) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogLine) ProtoMessage() {}

func (x *LogLine) ProtoReflect() protoreflect.Message {
	mi := &file_rebecca_node_v1_node_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogLine.ProtoReflect.Descriptor instead.
func (*LogLine) Descriptor() ([]byte, []int) {
	return file_rebecca_node_v1_node_proto_rawDescGZIP(), []int{26}
}

func (x *LogLine) GetStreamId() string {
	if x != nil {
		return x.StreamId
	}
	return ""
}

func (x *LogLine) GetLine() string {
	if x != nil {
		return x.Line
	}
	return ""
}

func (x *LogLine) GetEmittedAtUnix() int64 {
	if x != nil {
		return x.EmittedAtUnix
	}
	return 0
}

var File_rebecca_node_v1_node_proto protoreflect.FileDescriptor

const file_rebecca_node_v1_node_proto_rawDesc = "" +
	"\n" +
	"\x1arebecca/node/v1/node.proto\x12\x0frebecca.node.v1\"\a\n" +
	"\x05Empty\"R\n" +
	"\fHelloRequest\x12\x1b\n" +
	"\tmaster_id\x18\x01 \x01(\tR\bmasterId\x12%\n" +
	"\x0emaster_version\x18\x02 \x01(\tR\rmasterVersion\"\xeb\x01\n" +
	"\rHelloResponse\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x1b\n" +
	"\tnode_name\x18\x02 \x01(\tR\bnodeName\x12!\n" +
	"\fnode_version\x18\x03 \x01(\tR\vnodeVersion\x12!\n" +
	"\finstall_mode\x18\x04 \x01(\tR\vinstallMode\x12%\n" +
	"\x0eupdate_channel\x18\x05 \x01(\tR\rupdateChannel\x127\n" +
	"\aruntime\x18\x06 \x01(\v2\x1d.rebecca.node.v1.RuntimeStateR\aruntime\"\x82\x01\n" +
	"\x0eConnectRequest\x12\x1b\n" +
	"\tmaster_id\x18\x01 \x01(\tR\bmasterId\x12%\n" +
	"\x0emaster_version\x18\x02 \x01(\tR\rmasterVersion\x12,\n" +
	"\x12expected_node_name\x18\x03 \x01(\tR\x10expectedNodeName\"o\n" +
	"\x0fConnectResponse\x12#\n" +
	"\rconnection_id\x18\x01 \x01(\tR\fconnectionId\x127\n" +
	"\aruntime\x18\x02 \x01(\v2\x1d.rebecca.node.v1.RuntimeStateR\aruntime\"8\n" +
	"\rHealthRequest\x12'\n" +
	"\x0finclude_metrics\x18\x01 \x01(\bR\x0eincludeMetrics\"\x85\x01\n" +
	"\x0eHealthResponse\x127\n" +
	"\aruntime\x18\x01 \x01(\v2\x1d.rebecca.node.v1.RuntimeStateR\aruntime\x12:\n" +
	"\ametrics\x18\x02 \x01(\v2 .rebecca.node.v1.MetricsResponseR\ametrics\"\xf0\x01\n" +
	"\fRuntimeState\x12\x1c\n" +
	"\tconnected\x18\x01 \x01(\bR\tconnected\x12\x18\n" +
	"\astarted\x18\x02 \x01(\bR\astarted\x12!\n" +
	"\fcore_version\x18\x03 \x01(\tR\vcoreVersion\x12!\n" +
	"\fnode_version\x18\x04 \x01(\tR\vnodeVersion\x12!\n" +
	"\finstall_mode\x18\x05 \x01(\tR\vinstallMode\x12%\n" +
	"\x0eupdate_channel\x18\x06 \x01(\tR\rupdateChannel\x12\x18\n" +
	"\amessage\x18\a \x01(\tR\amessage\"\x84\x01\n" +
	"\x14RuntimeConfigRequest\x12!\n" +
	"\foperation_id\x18\x01 \x01(\tR\voperationId\x12\x1f\n" +
	"\vconfig_json\x18\x02 \x01(\tR\n" +
	"configJson\x12(\n" +
	"\x10include_db_users\x18\x03 \x01(\bR\x0eincludeDbUsers\"r\n" +
	"\x12StopRuntimeRequest\x12!\n" +
	"\foperation_id\x18\x01 \x01(\tR\voperationId\x129\n" +
	"\x19collect_usage_before_stop\x18\x02 \x01(\bR\x16collectUsageBeforeStop\"\xa9\x01\n" +
	"\x15RuntimeActionResponse\x12!\n" +
	"\foperation_id\x18\x01 \x01(\tR\voperationId\x12\x1a\n" +
	"\baccepted\x18\x02 \x01(\bR\baccepted\x127\n" +
	"\aruntime\x18\x03 \x01(\v2\x1d.rebecca.node.v1.RuntimeStateR\aruntime\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage\"\x8a\x01\n" +
	"\x12InboundUserRequest\x12!\n" +
	"\foperation_id\x18\x01 \x01(\tR\voperationId\x12\x1f\n" +
	"\vinbound_tag\x18\x02 \x01(\tR\n" +
	"inboundTag\x120\n" +
	"\x04user\x18\x03 \x01(\v2\x1c.rebecca.node.v1.InboundUserR\x04user\"t\n" +
	"\x18RemoveInboundUserRequest\x12!\n" +
	"\foperation_id\x18\x01 \x01(\tR\voperationId\x12\x1f\n" +
	"\vinbound_tag\x18\x02 \x01(\tR\n" +
	"inboundTag\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\"\xbc\x01\n" +
	"\vInboundUser\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\x1a\n" +
	"\bprotocol\x18\x02 \x01(\tR\bprotocol\x12@\n" +
	"\x06fields\x18\x03 \x03(\v2(.rebecca.node.v1.InboundUser.FieldsEntryR\x06fields\x1a9\n" +
	"\vFieldsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"9\n" +
	"\x0eMetricsRequest\x12'\n" +
	"\x0finclude_runtime\x18\x01 \x01(\bR\x0eincludeRuntime\"\xe8\x01\n" +
	"\x0fMetricsResponse\x127\n" +
	"\aruntime\x18\x01 \x01(\v2\x1d.rebecca.node.v1.RuntimeStateR\aruntime\x126\n" +
	"\x06system\x18\x02 \x01(\v2\x1e.rebecca.node.v1.SystemMetricsR\x06system\x12<\n" +
	"\btransfer\x18\x03 \x01(\v2 .rebecca.node.v1.TransferMetricsR\btransfer\x12&\n" +
	"\x0fsampled_at_unix\x18\x04 \x01(\x03R\rsampledAtUnix\"\xf8\x01\n" +
	"\rSystemMetrics\x12\x1b\n" +
	"\tcpu_cores\x18\x01 \x01(\x05R\bcpuCores\x12(\n" +
	"\x10cpu_frequency_hz\x18\x02 \x01(\x01R\x0ecpuFrequencyHz\x12*\n" +
	"\x11cpu_usage_percent\x18\x03 \x01(\x01R\x0fcpuUsagePercent\x12\x1f\n" +
	"\vmemory_used\x18\x04 \x01(\x04R\n" +
	"memoryUsed\x12!\n" +
	"\fmemory_total\x18\x05 \x01(\x04R\vmemoryTotal\x120\n" +
	"\x14memory_usage_percent\x18\x06 \x01(\x01R\x12memoryUsagePercent\"\xa5\x01\n" +
	"\x0fTransferMetrics\x12!\n" +
	"\fuplink_total\x18\x01 \x01(\x04R\vuplinkTotal\x12%\n" +
	"\x0edownlink_total\x18\x02 \x01(\x04R\rdownlinkTotal\x12!\n" +
	"\fupload_speed\x18\x03 \x01(\x04R\vuploadSpeed\x12%\n" +
	"\x0edownload_speed\x18\x04 \x01(\x04R\rdownloadSpeed\"N\n" +
	"\x13CollectUsageRequest\x12!\n" +
	"\fcollector_id\x18\x01 \x01(\tR\vcollectorId\x12\x14\n" +
	"\x05reset\x18\x02 \x01(\bR\x05reset\"c\n" +
	"\x0eUserUsageBatch\x12\x19\n" +
	"\bbatch_id\x18\x01 \x01(\tR\abatchId\x126\n" +
	"\x05stats\x18\x02 \x03(\v2 .rebecca.node.v1.UserUsageSampleR\x05stats\"9\n" +
	"\x0fUserUsageSample\x12\x10\n" +
	"\x03uid\x18\x01 \x01(\tR\x03uid\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x04R\x05value\"k\n" +
	"\x12OutboundUsageBatch\x12\x19\n" +
	"\bbatch_id\x18\x01 \x01(\tR\abatchId\x12:\n" +
	"\x05stats\x18\x02 \x03(\v2$.rebecca.node.v1.OutboundUsageSampleR\x05stats\"K\n" +
	"\x13OutboundUsageSample\x12\x10\n" +
	"\x03tag\x18\x01 \x01(\tR\x03tag\x12\x0e\n" +
	"\x02up\x18\x02 \x01(\x04R\x02up\x12\x12\n" +
	"\x04down\x18\x03 \x01(\x04R\x04down\",\n" +
	"\x0fAckUsageRequest\x12\x19\n" +
	"\bbatch_id\x18\x01 \x01(\tR\abatchId\"Q\n" +
	"\x10AckUsageResponse\x12\x19\n" +
	"\bbatch_id\x18\x01 \x01(\tR\abatchId\x12\"\n" +
	"\facknowledged\x18\x02 \x01(\bR\facknowledged\"\x83\x01\n" +
	"\x11StreamLogsRequest\x12\x1b\n" +
	"\tstream_id\x18\x01 \x01(\tR\bstreamId\x12\x1b\n" +
	"\tmax_lines\x18\x02 \x01(\rR\bmaxLines\x124\n" +
	"\x16flush_interval_seconds\x18\x03 \x01(\x01R\x14flushIntervalSeconds\"b\n" +
	"\aLogLine\x12\x1b\n" +
	"\tstream_id\x18\x01 \x01(\tR\bstreamId\x12\x12\n" +
	"\x04line\x18\x02 \x01(\tR\x04line\x12&\n" +
	"\x0femitted_at_unix\x18\x03 \x01(\x03R\remittedAtUnix2\xf5\x01\n" +
	"\x12NodeControlService\x12F\n" +
	"\x05Hello\x12\x1d.rebecca.node.v1.HelloRequest\x1a\x1e.rebecca.node.v1.HelloResponse\x12L\n" +
	"\aConnect\x12\x1f.rebecca.node.v1.ConnectRequest\x1a .rebecca.node.v1.ConnectResponse\x12I\n" +
	"\x06Health\x12\x1e.rebecca.node.v1.HealthRequest\x1a\x1f.rebecca.node.v1.HealthResponse2\xef\x05\n" +
	"\x12NodeRuntimeService\x12]\n" +
	"\fStartRuntime\x12%.rebecca.node.v1.RuntimeConfigRequest\x1a&.rebecca.node.v1.RuntimeActionResponse\x12_\n" +
	"\x0eRestartRuntime\x12%.rebecca.node.v1.RuntimeConfigRequest\x1a&.rebecca.node.v1.RuntimeActionResponse\x12Z\n" +
	"\vStopRuntime\x12#.rebecca.node.v1.StopRuntimeRequest\x1a&.rebecca.node.v1.RuntimeActionResponse\x12[\n" +
	"\n" +
	"SyncConfig\x12%.rebecca.node.v1.RuntimeConfigRequest\x1a&.rebecca.node.v1.RuntimeActionResponse\x12V\n" +
	"\aAddUser\x12#.rebecca.node.v1.InboundUserRequest\x1a&.rebecca.node.v1.RuntimeActionResponse\x12Y\n" +
	"\n" +
	"UpdateUser\x12#.rebecca.node.v1.InboundUserRequest\x1a&.rebecca.node.v1.RuntimeActionResponse\x12_\n" +
	"\n" +
	"RemoveUser\x12).rebecca.node.v1.RemoveInboundUserRequest\x1a&.rebecca.node.v1.RuntimeActionResponse\x12L\n" +
	"\aMetrics\x12\x1f.rebecca.node.v1.MetricsRequest\x1a .rebecca.node.v1.MetricsResponse2\xfe\x02\n" +
	"\x10NodeUsageService\x12Y\n" +
	"\x10CollectUserUsage\x12$.rebecca.node.v1.CollectUsageRequest\x1a\x1f.rebecca.node.v1.UserUsageBatch\x12S\n" +
	"\fAckUserUsage\x12 .rebecca.node.v1.AckUsageRequest\x1a!.rebecca.node.v1.AckUsageResponse\x12a\n" +
	"\x14CollectOutboundUsage\x12$.rebecca.node.v1.CollectUsageRequest\x1a#.rebecca.node.v1.OutboundUsageBatch\x12W\n" +
	"\x10AckOutboundUsage\x12 .rebecca.node.v1.AckUsageRequest\x1a!.rebecca.node.v1.AckUsageResponse2_\n" +
	"\x0fNodeLogsService\x12L\n" +
	"\n" +
	"StreamLogs\x12\".rebecca.node.v1.StreamLogsRequest\x1a\x18.rebecca.node.v1.LogLine0\x01BDZBgithub.com/rebeccapanel/rebecca-node/internal/proto/node/v1;nodev1b\x06proto3"

var (
	file_rebecca_node_v1_node_proto_rawDescOnce sync.Once
	file_rebecca_node_v1_node_proto_rawDescData []byte
)

func file_rebecca_node_v1_node_proto_rawDescGZIP() []byte {
	file_rebecca_node_v1_node_proto_rawDescOnce.Do(func() {
		file_rebecca_node_v1_node_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_rebecca_node_v1_node_proto_rawDesc), len(file_rebecca_node_v1_node_proto_rawDesc)))
	})
	return file_rebecca_node_v1_node_proto_rawDescData
}

var file_rebecca_node_v1_node_proto_msgTypes = make([]protoimpl.MessageInfo, 28)
var file_rebecca_node_v1_node_proto_goTypes = []any{
	(*Empty)(nil),                    // 0: rebecca.node.v1.Empty
	(*HelloRequest)(nil),             // 1: rebecca.node.v1.HelloRequest
	(*HelloResponse)(nil),            // 2: rebecca.node.v1.HelloResponse
	(*ConnectRequest)(nil),           // 3: rebecca.node.v1.ConnectRequest
	(*ConnectResponse)(nil),          // 4: rebecca.node.v1.ConnectResponse
	(*HealthRequest)(nil),            // 5: rebecca.node.v1.HealthRequest
	(*HealthResponse)(nil),           // 6: rebecca.node.v1.HealthResponse
	(*RuntimeState)(nil),             // 7: rebecca.node.v1.RuntimeState
	(*RuntimeConfigRequest)(nil),     // 8: rebecca.node.v1.RuntimeConfigRequest
	(*StopRuntimeRequest)(nil),       // 9: rebecca.node.v1.StopRuntimeRequest
	(*RuntimeActionResponse)(nil),    // 10: rebecca.node.v1.RuntimeActionResponse
	(*InboundUserRequest)(nil),       // 11: rebecca.node.v1.InboundUserRequest
	(*RemoveInboundUserRequest)(nil), // 12: rebecca.node.v1.RemoveInboundUserRequest
	(*InboundUser)(nil),              // 13: rebecca.node.v1.InboundUser
	(*MetricsRequest)(nil),           // 14: rebecca.node.v1.MetricsRequest
	(*MetricsResponse)(nil),          // 15: rebecca.node.v1.MetricsResponse
	(*SystemMetrics)(nil),            // 16: rebecca.node.v1.SystemMetrics
	(*TransferMetrics)(nil),          // 17: rebecca.node.v1.TransferMetrics
	(*CollectUsageRequest)(nil),      // 18: rebecca.node.v1.CollectUsageRequest
	(*UserUsageBatch)(nil),           // 19: rebecca.node.v1.UserUsageBatch
	(*UserUsageSample)(nil),          // 20: rebecca.node.v1.UserUsageSample
	(*OutboundUsageBatch)(nil),       // 21: rebecca.node.v1.OutboundUsageBatch
	(*OutboundUsageSample)(nil),      // 22: rebecca.node.v1.OutboundUsageSample
	(*AckUsageRequest)(nil),          // 23: rebecca.node.v1.AckUsageRequest
	(*AckUsageResponse)(nil),         // 24: rebecca.node.v1.AckUsageResponse
	(*StreamLogsRequest)(nil),        // 25: rebecca.node.v1.StreamLogsRequest
	(*LogLine)(nil),                  // 26: rebecca.node.v1.LogLine
	nil,                              // 27: rebecca.node.v1.InboundUser.FieldsEntry
}
var file_rebecca_node_v1_node_proto_depIdxs = []int32{
	7,  // 0: rebecca.node.v1.HelloResponse.runtime:type_name -> rebecca.node.v1.RuntimeState
	7,  // 1: rebecca.node.v1.ConnectResponse.runtime:type_name -> rebecca.node.v1.RuntimeState
	7,  // 2: rebecca.node.v1.HealthResponse.runtime:type_name -> rebecca.node.v1.RuntimeState
	15, // 3: rebecca.node.v1.HealthResponse.metrics:type_name -> rebecca.node.v1.MetricsResponse
	7,  // 4: rebecca.node.v1.RuntimeActionResponse.runtime:type_name -> rebecca.node.v1.RuntimeState
	13, // 5: rebecca.node.v1.InboundUserRequest.user:type_name -> rebecca.node.v1.InboundUser
	27, // 6: rebecca.node.v1.InboundUser.fields:type_name -> rebecca.node.v1.InboundUser.FieldsEntry
	7,  // 7: rebecca.node.v1.MetricsResponse.runtime:type_name -> rebecca.node.v1.RuntimeState
	16, // 8: rebecca.node.v1.MetricsResponse.system:type_name -> rebecca.node.v1.SystemMetrics
	17, // 9: rebecca.node.v1.MetricsResponse.transfer:type_name -> rebecca.node.v1.TransferMetrics
	20, // 10: rebecca.node.v1.UserUsageBatch.stats:type_name -> rebecca.node.v1.UserUsageSample
	22, // 11: rebecca.node.v1.OutboundUsageBatch.stats:type_name -> rebecca.node.v1.OutboundUsageSample
	1,  // 12: rebecca.node.v1.NodeControlService.Hello:input_type -> rebecca.node.v1.HelloRequest
	3,  // 13: rebecca.node.v1.NodeControlService.Connect:input_type -> rebecca.node.v1.ConnectRequest
	5,  // 14: rebecca.node.v1.NodeControlService.Health:input_type -> rebecca.node.v1.HealthRequest
	8,  // 15: rebecca.node.v1.NodeRuntimeService.StartRuntime:input_type -> rebecca.node.v1.RuntimeConfigRequest
	8,  // 16: rebecca.node.v1.NodeRuntimeService.RestartRuntime:input_type -> rebecca.node.v1.RuntimeConfigRequest
	9,  // 17: rebecca.node.v1.NodeRuntimeService.StopRuntime:input_type -> rebecca.node.v1.StopRuntimeRequest
	8,  // 18: rebecca.node.v1.NodeRuntimeService.SyncConfig:input_type -> rebecca.node.v1.RuntimeConfigRequest
	11, // 19: rebecca.node.v1.NodeRuntimeService.AddUser:input_type -> rebecca.node.v1.InboundUserRequest
	11, // 20: rebecca.node.v1.NodeRuntimeService.UpdateUser:input_type -> rebecca.node.v1.InboundUserRequest
	12, // 21: rebecca.node.v1.NodeRuntimeService.RemoveUser:input_type -> rebecca.node.v1.RemoveInboundUserRequest
	14, // 22: rebecca.node.v1.NodeRuntimeService.Metrics:input_type -> rebecca.node.v1.MetricsRequest
	18, // 23: rebecca.node.v1.NodeUsageService.CollectUserUsage:input_type -> rebecca.node.v1.CollectUsageRequest
	23, // 24: rebecca.node.v1.NodeUsageService.AckUserUsage:input_type -> rebecca.node.v1.AckUsageRequest
	18, // 25: rebecca.node.v1.NodeUsageService.CollectOutboundUsage:input_type -> rebecca.node.v1.CollectUsageRequest
	23, // 26: rebecca.node.v1.NodeUsageService.AckOutboundUsage:input_type -> rebecca.node.v1.AckUsageRequest
	25, // 27: rebecca.node.v1.NodeLogsService.StreamLogs:input_type -> rebecca.node.v1.StreamLogsRequest
	2,  // 28: rebecca.node.v1.NodeControlService.Hello:output_type -> rebecca.node.v1.HelloResponse
	4,  // 29: rebecca.node.v1.NodeControlService.Connect:output_type -> rebecca.node.v1.ConnectResponse
	6,  // 30: rebecca.node.v1.NodeControlService.Health:output_type -> rebecca.node.v1.HealthResponse
	10, // 31: rebecca.node.v1.NodeRuntimeService.StartRuntime:output_type -> rebecca.node.v1.RuntimeActionResponse
	10, // 32: rebecca.node.v1.NodeRuntimeService.RestartRuntime:output_type -> rebecca.node.v1.RuntimeActionResponse
	10, // 33: rebecca.node.v1.NodeRuntimeService.StopRuntime:output_type -> rebecca.node.v1.RuntimeActionResponse
	10, // 34: rebecca.node.v1.NodeRuntimeService.SyncConfig:output_type -> rebecca.node.v1.RuntimeActionResponse
	10, // 35: rebecca.node.v1.NodeRuntimeService.AddUser:output_type -> rebecca.node.v1.RuntimeActionResponse
	10, // 36: rebecca.node.v1.NodeRuntimeService.UpdateUser:output_type -> rebecca.node.v1.RuntimeActionResponse
	10, // 37: rebecca.node.v1.NodeRuntimeService.RemoveUser:output_type -> rebecca.node.v1.RuntimeActionResponse
	15, // 38: rebecca.node.v1.NodeRuntimeService.Metrics:output_type -> rebecca.node.v1.MetricsResponse
	19, // 39: rebecca.node.v1.NodeUsageService.CollectUserUsage:output_type -> rebecca.node.v1.UserUsageBatch
	24, // 40: rebecca.node.v1.NodeUsageService.AckUserUsage:output_type -> rebecca.node.v1.AckUsageResponse
	21, // 41: rebecca.node.v1.NodeUsageService.CollectOutboundUsage:output_type -> rebecca.node.v1.OutboundUsageBatch
	24, // 42: rebecca.node.v1.NodeUsageService.AckOutboundUsage:output_type -> rebecca.node.v1.AckUsageResponse
	26, // 43: rebecca.node.v1.NodeLogsService.StreamLogs:output_type -> rebecca.node.v1.LogLine
	28, // [28:44] is the sub-list for method output_type
	12, // [12:28] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_rebecca_node_v1_node_proto_init() }
func file_rebecca_node_v1_node_proto_init() {
	if File_rebecca_node_v1_node_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_rebecca_node_v1_node_proto_rawDesc), len(file_rebecca_node_v1_node_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   28,
			NumExtensions: 0,
			NumServices:   4,
		},
		GoTypes:           file_rebecca_node_v1_node_proto_goTypes,
		DependencyIndexes: file_rebecca_node_v1_node_proto_depIdxs,
		MessageInfos:      file_rebecca_node_v1_node_proto_msgTypes,
	}.Build()
	File_rebecca_node_v1_node_proto = out.File
	file_rebecca_node_v1_node_proto_goTypes = nil
	file_rebecca_node_v1_node_proto_depIdxs = nil
}
